[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false

[[bin]]
name = "xtask"
path = "src/main.rs"

[lib]
name = "xtask"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
roxmltree = "0.21"
regex = "1"
copybook-core = { path = "../copybook-core" }
serde_plain = "1.0.2"
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.23.0"
