[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Project automation xtasks for copybook-rs"
publish = false

[[bin]]
name = "xtask"
path = "src/main.rs"

[lib]
name = "xtask"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
roxmltree = "0.21"
regex = "1"
copybook-core = { path = "../copybook-core" }
serde_plain = "1.0.2"
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.23.0"
